package com.booking.entities;

import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;

import java.time.LocalTime;
import java.util.List;


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


@Entity
@Data
@NoArgsConstructor
public class Bus {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private String type;
    private int availableSeats;
    private String source;
    private String destination;
    private LocalTime departureTime;
    private LocalTime arrivalTime;
    private double fare;
    private List<String> amenities;

    // Constructors, getters, and setters are automatically generated by Lombok
}

